[package]
name = "aeroswiper"
version = "0.1.0"
edition = "2021"

[lib]
name = "aeroswiper"
path = "src/lib.rs"

[[bin]]
name = "aeroswiper"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
panic = "abort"
